site_name: The FastAPI Expert
site_url: https://fastapiexpert.com
site_author: Marcelo Trylesinski
copyright: Copyright &copy; 2023 Marcelo Trylesinski

repo_name: Kludex/monorepo
repo_url: https://github.com/Kludex/monorepo
edit_uri: edit/main/docs/

theme:
  name: material
  locale: en
  icon:
    repo: fontawesome/brands/github
    logo: material/trophy
  features:
    - navigation.tabs
    - content.code.annotate

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: red
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      primary: red
      toggle:
        icon: material/lightbulb-outline
        name: Switch to system preference

plugins:
  - meta
  - search
  - tags
  - social
  - blog:
      blog_dir: blog/

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home:
      - About: index.md
      - Talks: talks.md
  - Blog:
      - blog/index.md

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/marcelotryle
    - icon: fontawesome/brands/github
      link: https://github.com/kludex
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/marcelotryle/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UC91TdNbobUqT3d2CHcTkx8A
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/marcelotryle/
    - icon: fontawesome/solid/envelope
      link: mailto:marcelotryle@gmail.com
