[project]
name = "monorepo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tool.uv]
package = false
dev-dependencies = [
    "fastapi",
    "uvicorn",
    "httpx",
    # Linting
    "ruff",
]

[tool.ruff]
select = ["I"]
